module.exports = {
    AUTH_TABLE_FILENAME : "AuthTable.json",
    //------- CONTENT DISPLAY NAMES -------//
    INITIAL_CONTENT : "INITIAL_CONTENT",
    NEW_ACCOUNT_PANE : "NEW_ACCOUNT_PANE",
    HOME_VIEW : "HOME_VIEW",
    SIGNIN_PANE : "SIGNIN_PANE",
    SETTINGS_PANE : "SETTINGS_PANE",
    NEW_SERVER_INSTANCE_WINDOW : "NEW_SERVER_INSTANCE_WINDOW",
    NEW_APP_INSTANCE_WINDOW : "NEW_APP_INSTANCE_WINDOW"
}