module.exports = {
    AUTH_TABLE_FILENAME : "AuthTable.json",
    AUTH_OPTION_PERMISSION_KEY : "AUTH_OPTION_PERMISSION_KEY",
    AUTH_OPTION_PASSWORD : "AUTH_OPTION_PASSWORD",
    AUTH_OPTION_PERMISSION_KEY_AND_PASSWORD : "AUTH_OPTION_PERMISSION_KEY_AND_PASSWORD",
    //------- CONTENT DISPLAY NAMES -------//
    INITIAL_CONTENT : "INITIAL_CONTENT",
    NEW_ACCOUNT_PANE : "NEW_ACCOUNT_PANE",
    HOME_VIEW : "HOME_VIEW",
    SIGNIN_PANE : "SIGNIN_PANE",
    SETTINGS_PANE : "SETTINGS_PANE",
    FILE_SYSTEM_VIEW: "FILE_SYSTEM_VIEW",
    NEW_SERVER_INSTANCE_WINDOW : "NEW_SERVER_INSTANCE_WINDOW",
    NEW_APP_INSTANCE_WINDOW : "NEW_APP_INSTANCE_WINDOW"
}